include_recipe 'server_boilerplate::base'
include_recipe 'server_boilerplate::languages'
include_recipe 'server_boilerplate::db'
include_recipe 'server_boilerplate::server'
include_recipe 'server_boilerplate::ci'
